baseURL = "https://hugo-forestry-template.vercel.app/"
languageCode = "en-us"
title = "Hugo Forestry Demo"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    name = "Single"
    url = "/template-test/"
    weight = -100